#!/bin/bash

# Deploy R36S Viewer package to SD card automatically
# Run this in WSL after prepare_final_r36s_package.sh

set -e

echo "=== R36S Viewer Auto-Deploy to SD Card ==="
echo

# Check if package exists
PACKAGE_FILE="r36s_viewer_final_package.tar.gz"
if [ ! -f "$PACKAGE_FILE" ]; then
    echo "ERROR: Package not found: $PACKAGE_FILE"
    echo "Run ./prepare_final_r36s_package.sh first"
    exit 1
fi

echo "✓ Found package: $PACKAGE_FILE ($(ls -lh $PACKAGE_FILE | awk '{print $5}'))"

# Common Windows drive mount points in WSL
R36S_DRIVES=(
    "/mnt/d"    # Most common
    "/mnt/e"
    "/mnt/f"
    "/mnt/g"
)

# Find R36S SD card
R36S_MOUNT=""
for drive in "${R36S_DRIVES[@]}"; do
    if [ -d "$drive" ]; then
        # Check if it looks like R36S by looking for common indicators
        if [ -d "$drive/RetroArch" ] || [ -d "$drive/EASYROMS" ] || [ -d "$drive/apps" ] || [[ "$(ls $drive 2>/dev/null)" =~ (retroarch|roms|apps) ]]; then
            R36S_MOUNT="$drive"
            echo "✓ Found R36S SD card: $drive"
            break
        fi
    fi
done

if [ -z "$R36S_MOUNT" ]; then
    echo "⚠ R36S SD card not auto-detected"
    echo
    echo "Available drives:"
    for drive in "${R36S_DRIVES[@]}"; do
        if [ -d "$drive" ]; then
            echo "  $drive: $(ls $drive 2>/dev/null | head -3 | tr '\n' ' ')..."
        else
            echo "  $drive: not mounted"
        fi
    done
    echo
    read -p "Enter R36S SD card path (e.g., /mnt/d): " R36S_MOUNT
    
    if [ ! -d "$R36S_MOUNT" ]; then
        echo "ERROR: Directory not found: $R36S_MOUNT"
        exit 1
    fi
fi

echo "Using R36S mount: $R36S_MOUNT"

# Create installation directory
INSTALL_DIR="$R36S_MOUNT/r36s_viewer_install"
echo
echo "Creating installation directory: $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"

# Copy package to SD card
echo "Copying package to SD card..."
cp "$PACKAGE_FILE" "$INSTALL_DIR/"
echo "✓ Package copied to SD card"

# Extract package on SD card (saves space and time on R36S)
echo "Extracting package on SD card..."
cd "$INSTALL_DIR"
tar xzf "$PACKAGE_FILE"
rm "$PACKAGE_FILE"  # Remove archive after extraction

echo "✓ Package extracted and cleaned up"

# Create quick install script on SD card root
cd "$R36S_MOUNT"
cat > quick_install_r36s_viewer.sh << 'EOF'
#!/bin/bash
# Quick installer for R36S Viewer
# Run this script on R36S console

echo "=== R36S Viewer Quick Install ==="
echo

# Check if we're on the R36S (ARM architecture)
if ! uname -m | grep -q arm; then
    echo "WARNING: This doesn't appear to be an ARM system"
    echo "Make sure you're running this on the R36S console"
fi

# Navigate to installation directory
cd "$(dirname "$0")/r36s_viewer_install/r36s_viewer_final_package"

if [ ! -f "install_r36s_viewer.sh" ]; then
    echo "ERROR: Installation files not found"
    echo "Make sure the SD card was properly prepared"
    exit 1
fi

echo "Found installation files, proceeding..."
echo

# Run the installer
sudo ./install_r36s_viewer.sh

echo
echo "=== Installation Complete! ==="
echo "You can now use: r36s_viewer"
echo
echo "Controls:"
echo "  A: Next image     | Start: Toggle subtitles"  
echo "  B: Previous image | Select: Menu/Exit"
echo "  L/R: Fast navigation"
echo
echo "Examples:"
echo "  r36s_viewer                 # Show episode menu"
echo "  r36s_viewer chaves001       # View specific episode"
echo "  r36s_viewer --windowed      # Debug mode"
EOF

chmod +x quick_install_r36s_viewer.sh
echo "✓ Created quick installer on SD card root"

# Create README for user
cat > R36S_VIEWER_README.txt << 'EOF'
R36S Viewer - Installation Instructions
=======================================

Your R36S Viewer has been prepared and is ready to install!

INSTALLATION ON R36S CONSOLE:
1. Insert this SD card into your R36S
2. Boot the R36S console  
3. Open terminal or SSH to R36S
4. Run: ./quick_install_r36s_viewer.sh
5. The installer will handle everything automatically

MANUAL INSTALLATION:
If the quick installer doesn't work:
1. cd r36s_viewer_install/r36s_viewer_final_package
2. sudo ./install_r36s_viewer.sh

USAGE AFTER INSTALLATION:
- r36s_viewer                 # Show episode menu
- r36s_viewer chaves001       # View specific episode  
- r36s_viewer --windowed      # Debug mode

CONTROLS:
- A/X: Next image
- B/Y: Previous image
- Start: Toggle subtitle display
- Select: Toggle menu/exit
- L/R: Fast navigation (5 images)

UNINSTALL:
To remove: sudo ./uninstall_r36s_viewer.sh

For support, check the build logs or try manual compilation.
Generated by R36S Viewer Auto-Deploy Script
EOF

echo "✓ Created user README"

cd - > /dev/null  # Return to original directory

echo
echo "=== Auto-Deploy Complete! ==="
echo
echo "📁 Files on SD card:"
echo "   $R36S_MOUNT/quick_install_r36s_viewer.sh"
echo "   $R36S_MOUNT/R36S_VIEWER_README.txt" 
echo "   $R36S_MOUNT/r36s_viewer_install/"
echo
echo "💾 SD card is ready! On your R36S console:"
echo "   1. Insert SD card"
echo "   2. Boot R36S"  
echo "   3. Run: ./quick_install_r36s_viewer.sh"
echo "   4. Use: r36s_viewer"
echo
echo "🎮 The viewer will be installed and ready to use!"
echo "   Total size on SD: $(du -sh $INSTALL_DIR | cut -f1)"

# Show final summary
echo
echo "🎯 Summary:"
echo "   ✅ Package prepared and copied"
echo "   ✅ Auto-installer created"  
echo "   ✅ Documentation included"
echo "   ✅ Ready for R36S deployment"
echo
echo "Enjoy your subtitle viewer on R36S! 🎬✨"
